{
 "title": "Flight Tracking Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "PiAware Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "piaware_service_state{job=\"piaware_exporter\"} == 1",
     "legendFormat": "{{piaware_service_state}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "piaware_radio_state{job=\"piaware_exporter\"} == 1",
     "legendFormat": "{{piaware_radio_state}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "piaware_connect_to_flightaware_state{job=\"piaware_exporter\"} == 1",
     "legendFormat": "{{piaware_connect_to_flightaware_state}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "piaware_mlat_state{job=\"piaware_exporter\"} == 1",
     "legendFormat": "{{piaware_mlat_state}}"
    }
   ]
  },
  {
   "title": "Current dump1090-fa Aircraft Tracking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Current Aircraft Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_observed{job=\"dump1090\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Aircraft W/ Position",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_with_position{job=\"dump1090\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Maximum Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "NM" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_max_range{job=\"dump1090\", time_period=\"latest\"} / 1852"
    }
   ]
  },
  {
   "title": "Messages Received / Second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(dump1090_messages_total{job=\"dump1090\", time_period=\"latest\"}[1m])"
    }
   ]
  },
  {
   "title": "Signal Peak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dbFS" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dump1090_stats_local_peak_signal_strength_dbFS{job=\"dump1090\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "Signal Mean",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dbFS" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dump1090_stats_local_signal_strength_dbFS{job=\"dump1090\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "dump1090-fa Historical Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Aircraft Seen",
   "type": "timeseries",
   "description": "Total aircraft seen by the receiver at the given point in time. Filtered aircraft to only those that have been seen within the last 15 seconds to minimize contributions from stale aircraft. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_observed{time_period=\"latest\"}",
     "legendFormat": "Total Aircraft"
    },
    {
     "expr": "dump1090_recent_aircraft_with_position{time_period=\"latest\"}",
     "legendFormat": "Aircraft with ADS-B Position"
    },
    {
     "expr": "dump1090_recent_aircraft_with_multilateration{time_period=\"latest\"}",
     "legendFormat": "Aircraft with MLAT Position"
    },
    {
     "expr": "dump1090_recent_aircraft_observed{time_period=\"latest\"} - dump1090_recent_aircraft_with_position{time_period=\"latest\"}",
     "legendFormat": "Aircraft without Position"
    }
   ]
  },
  {
   "title": "Message Rate Received",
   "type": "timeseries",
   "description": "Messages received per second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dump1090_stats_messages_total{job=\"dump1090\", time_period=\"last1min\"} / 60",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Maximum Range",
   "type": "timeseries",
   "description": "Maximum range of the currently observed aircraft at the given time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_max_range{job=\"dump1090\", time_period=\"latest\"} / 1852",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Signal Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "dump1090_stats_local_peak_signal_strength_dbFS{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "Peak Signal"
    },
    {
     "expr": "dump1090_stats_local_signal_strength_dbFS{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "Mean Signal"
    },
    {
     "expr": "dump1090_stats_local_noise_level_dbFS{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "Noise Level"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Demodulator - Time spent demodulating and decoding data from the USB SDR dongle. \n\nUSB -  Time spent reading sample data from the USB SDR dongle. \n\nOther - Time spent doing network I/O, processing network messages, and periodic tasks.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dump1090_stats_cpu_demod_milliseconds{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "Demodulator"
    },
    {
     "expr": "dump1090_stats_cpu_reader_milliseconds{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "USB"
    },
    {
     "expr": "dump1090_stats_cpu_background_milliseconds{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "Other (Network I/O, periodic tasks, etc)"
    }
   ]
  }
 ]
}